- name: Configure the minecraft server infra
  hosts: minecraft_server
  collections:
    - devsec.hardening
    - ansible.posix
    - community.docker
  roles:
    - { role: copy_ssh_key, tags: copy_ssh_key }
    - { role: ssh_hardening, tags: ssh_hardening }
    - { role: core, tags: core }
    - { role: docker, tags: docker }
  tasks:
    - name: Allow Minecraft server port in firewall
      become: true
      ansible.builtin.command: ufw allow 25565
  vars:
    ssh_pam_support: false
    ssh_use_pam: false
    ssh_kerberos_support: false
    ssh_server_password_login: false
    sshd_authenticationmethods: publickey
    ssh_permit_root_login: without-password
