---
- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt with the new cache and install docker-ce
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true
  notify: "restart docker service"

- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install the Python docker library
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Make sure the Docker service is started
  become: true
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    masked: false


- name: Add Ansible user to docker group ({{ ansible_user }})
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
